### ISSUE TITLE
Memory Allocation Error when running -BLS command

### ISSUE THREAD

**Issue by llamicron** [joeldhartman/vartools#1]
Platform: MacOS Mojave 10.14.2
VARTOOLS version 1.36

When running the following command: 
```
$ vartools -l /path/to/lc_list -ascii -oneline -BLS q 0.01 0.1 0.1 2.0 100000 200 -6 3 1 /path/to/outdir 1 /path/to/outdir 0 fittrap nobinnedrms ophcurve /path/to/outdir -0.1 1.1 0.001
```
I get the following output:
```
vartools(45112,0x10f7b75c0) malloc: can't allocate region
*** mach_vm_map(size=18446744073709465600) failed (error code=3)
vartools(45112,0x10f7b75c0) malloc: *** set a breakpoint in malloc_error_break to debug
Memory Allocation Error
```

I've tried this on multiple different data sets, doesn't seem to have any effect.

Running another command like `-LS` works just fine, seems to only affect `-BLS`.

I see that in version 1.35 a memory allocation error was fixed for the `-BLS` command, but this is version 1.36

Still new to this, I can provide any additional details if I need to.

**Comment by llamicron** [comment]
Just tested on version 1.38, same result

**Comment by joeldhartman** [comment]
The problem stems from a bug in handling light curves where the total time span is less than the minimum period given to BLS.  I have commited a new version of processcommand.c which checks for and skips light curves where this occurs.
